name: Test-k8s-deployment
#description: First tests on deploying to a k8s cluster during action workflow
on: push

jobs:
  deploy-to-k8s-locally:
    name: test k8s trigger
    runs-on: [self-hosted, ubuntu, michael]
    permissions:
      security-events: write
      actions: read

    steps:
      - name: checkout code for manifest files
        uses: actions/checkout@v3
      - name: Deploy first manifest to cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: default
          manifests:
            kubernetes/service.yaml
    