name: Context testing
on: push
jobs:
  dump_contexts_to_log:
    runs-on: [self-hosted, ubuntu]
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo "${{ github.repository_owner_id }} OR $GITHUB_REPOSITORY_OWNER"
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: test something here
        run: echo 'hello'
      - name: Run custom actions
        id: mycustomaction
        uses: ./.github/actions/hello-world-action/
        with:
          level: 200
      - name: Print custom output 2
        run: echo "${{ steps.mycustomaction.outputs.random-number)}}